foo='hello world'
echo ${foo:0}
echo ${foo:12}
echo ${foo:1:}
echo ${foo:1:3}
echo ${foo/}
echo ${foo/he}
echo ${foo/he/}
echo ${foo/he/she}
echo ${foo//}
echo ${foo//he}
echo ${foo//he/}
echo ${foo//he/she}
echo ${#foo}
